/**
 * The 7 Documented Failure Scenarios for Interactive Testing & Live Demos.
 */
import { RecoveryRequestData } from "./risk-service";

export interface FailureScenarioDefinition {
  id: string;
  name: string;
  tag: string;
  summary: string;
  expectedOutcome: "APPROVE" | "MANUAL_REVIEW" | "DENY";
  request: RecoveryRequestData;
}

export const FAILURE_SCENARIOS: FailureScenarioDefinition[] = [
  {
    id: "scen-1",
    name: "Scenario 1: Missing Device Data",
    tag: "Ablation / Missing Data",
    summary: "User lost their smartphone over the weekend; device fingerprint and hardware trust are entirely absent.",
    expectedOutcome: "MANUAL_REVIEW",
    request: {
      request_id: "req-scen-01",
      user_id: "u104829",
      role: "Student",
      recovery_reason: "lost_device",
      device_id: "",
      device_known: false,
      device_trust_score: 0.0,
      device_change: true,
      ip_risk_score: 0.12,
      geo_consistency: 0.92,
      login_history_consistency: 0.85,
      identity_evidence_available: true,
      identity_evidence_score: 0.88,
      directory_status: "ACTIVE",
      mfa_history: "ACTIVE_HEALTHY",
      recovery_velocity: 0,
      source_missing: "device",
      ground_truth: "LEGITIMATE",
      expected_decision: "MANUAL_REVIEW",
    },
  },
  {
    id: "scen-2",
    name: "Scenario 2: Delayed Identity & Directory Sync",
    tag: "Latency / Delayed Data",
    summary: "Faculty member reset phone while travel verification / LDAP sync is delayed in ingestion queues.",
    expectedOutcome: "MANUAL_REVIEW",
    request: {
      request_id: "req-scen-02",
      user_id: "f302914",
      role: "Faculty",
      recovery_reason: "mfa_phone_replaced",
      device_id: "dev_macbook_faculty",
      device_known: true,
      device_trust_score: 0.90,
      device_change: false,
      ip_risk_score: 0.15,
      geo_consistency: 0.85,
      login_history_consistency: 0.80,
      identity_evidence_available: true,
      identity_evidence_score: 0.85,
      directory_status: "ACTIVE",
      mfa_history: "RECENTLY_RESET",
      recovery_velocity: 1,
      evidence_delay: true,
      source_delayed: "identity",
      ground_truth: "LEGITIMATE",
      expected_decision: "MANUAL_REVIEW",
    },
  },
  {
    id: "scen-3",
    name: "Scenario 3: Credential Stuffing & Bot Takeover",
    tag: "Adversarial Attack",
    summary: "Attacker using residential proxy / Tor node with breached credentials and elevated recovery velocity.",
    expectedOutcome: "DENY",
    request: {
      request_id: "req-scen-03",
      user_id: "u902183",
      role: "Student",
      recovery_reason: "forgot_password",
      device_id: "dev_bot_headless",
      device_known: false,
      device_trust_score: 0.10,
      device_change: true,
      ip_risk_score: 0.94,
      geo_consistency: 0.08,
      login_history_consistency: 0.05,
      identity_evidence_available: false,
      identity_evidence_score: 0.0,
      directory_status: "ACTIVE",
      mfa_history: "FAILED_RECENTLY",
      recovery_velocity: 4,
      fraud_scenario: "credential_stuffing",
      ground_truth: "FRAUD",
      expected_decision: "DENY",
    },
  },
  {
    id: "scen-4",
    name: "Scenario 4: Conflicting Telemetry (Trusted Device, Tor IP)",
    tag: "Session Hijack / Conflict",
    summary: "Known laptop fingerprint paired with a hostile foreign VPN / Tor exit node and anomalous location.",
    expectedOutcome: "MANUAL_REVIEW",
    request: {
      request_id: "req-scen-04",
      user_id: "u550192",
      role: "Student",
      recovery_reason: "locked_out_traveling",
      device_id: "dev_known_student_dell",
      device_known: true,
      device_trust_score: 0.95,
      device_change: false,
      ip_risk_score: 0.88,
      geo_consistency: 0.15,
      login_history_consistency: 0.40,
      identity_evidence_available: true,
      identity_evidence_score: 0.80,
      directory_status: "ACTIVE",
      mfa_history: "ACTIVE_HEALTHY",
      recovery_velocity: 1,
      fraud_scenario: "none",
      ground_truth: "FRAUD",
      expected_decision: "MANUAL_REVIEW",
    },
  },
  {
    id: "scen-5",
    name: "Scenario 5: High Recovery Velocity (Reset Bombardment)",
    tag: "Brute Force / Velocity",
    summary: "Multiple consecutive recovery attempts within minutes, triggering automated denial circuits.",
    expectedOutcome: "DENY",
    request: {
      request_id: "req-scen-05",
      user_id: "f882103",
      role: "Faculty",
      recovery_reason: "session_expired_urgent",
      device_id: "dev_unknown_browser",
      device_known: false,
      device_trust_score: 0.45,
      device_change: true,
      ip_risk_score: 0.55,
      geo_consistency: 0.60,
      login_history_consistency: 0.50,
      identity_evidence_available: true,
      identity_evidence_score: 0.70,
      directory_status: "ACTIVE",
      mfa_history: "FAILED_RECENTLY",
      recovery_velocity: 5,
      fraud_scenario: "social_engineering",
      ground_truth: "FRAUD",
      expected_decision: "DENY",
    },
  },
  {
    id: "scen-6",
    name: "Scenario 6: Multiple Telemetry Sources Unavailable",
    tag: "Degraded Telemetry",
    summary: "Temporary researcher requesting access with zero device history and unsubmitted identity documents.",
    expectedOutcome: "DENY",
    request: {
      request_id: "req-scen-06",
      user_id: "r110482",
      role: "Temporary Researcher",
      recovery_reason: "forgot_password",
      device_id: "",
      device_known: false,
      device_trust_score: 0.0,
      device_change: true,
      ip_risk_score: 0.35,
      geo_consistency: 0.50,
      login_history_consistency: 0.20,
      identity_evidence_available: false,
      identity_evidence_score: 0.0,
      directory_status: "PENDING_REVIEW",
      mfa_history: "DISABLED",
      recovery_velocity: 1,
      source_missing: "multiple",
      ground_truth: "FRAUD",
      expected_decision: "DENY",
    },
  },
  {
    id: "scen-7",
    name: "Scenario 7: Suspended Directory Account",
    tag: "Insider Threat / Suspension",
    summary: "Student or employee with administrative disciplinary suspension attempting credential override.",
    expectedOutcome: "DENY",
    request: {
      request_id: "req-scen-07",
      user_id: "u330192",
      role: "Student",
      recovery_reason: "forgot_password",
      device_id: "dev_dorm_desktop",
      device_known: true,
      device_trust_score: 0.90,
      device_change: false,
      ip_risk_score: 0.10,
      geo_consistency: 0.95,
      login_history_consistency: 0.90,
      identity_evidence_available: true,
      identity_evidence_score: 0.95,
      directory_status: "SUSPENDED",
      mfa_history: "DISABLED",
      recovery_velocity: 0,
      fraud_scenario: "insider_threat",
      ground_truth: "FRAUD",
      expected_decision: "DENY",
    },
  },
];
